// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "libnutrition/proto/service/composite_food_messages.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CompositeFoodLoadRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CompositeFoodLoadRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* CompositeFoodLoadResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CompositeFoodLoadResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* CompositeFoodStoreRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CompositeFoodStoreRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* CompositeFoodStoreResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CompositeFoodStoreResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* CompositeFoodDeleteRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CompositeFoodDeleteRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* CompositeFoodDeleteResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CompositeFoodDeleteResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto() {
  protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "libnutrition/proto/service/composite_food_messages.proto");
  GOOGLE_CHECK(file != NULL);
  CompositeFoodLoadRequest_descriptor_ = file->message_type(0);
  static const int CompositeFoodLoadRequest_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadRequest, omit_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadRequest, omitexpired_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadRequest, nameandidonly_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadRequest, includedatesinname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadRequest, requestedids_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadRequest, requesteduserids_),
  };
  CompositeFoodLoadRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CompositeFoodLoadRequest_descriptor_,
      CompositeFoodLoadRequest::default_instance_,
      CompositeFoodLoadRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CompositeFoodLoadRequest));
  CompositeFoodLoadResponse_descriptor_ = file->message_type(1);
  static const int CompositeFoodLoadResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadResponse, compositefoods_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadResponse, error_),
  };
  CompositeFoodLoadResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CompositeFoodLoadResponse_descriptor_,
      CompositeFoodLoadResponse::default_instance_,
      CompositeFoodLoadResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodLoadResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CompositeFoodLoadResponse));
  CompositeFoodStoreRequest_descriptor_ = file->message_type(2);
  static const int CompositeFoodStoreRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodStoreRequest, compositefoods_),
  };
  CompositeFoodStoreRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CompositeFoodStoreRequest_descriptor_,
      CompositeFoodStoreRequest::default_instance_,
      CompositeFoodStoreRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodStoreRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodStoreRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CompositeFoodStoreRequest));
  CompositeFoodStoreResponse_descriptor_ = file->message_type(3);
  static const int CompositeFoodStoreResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodStoreResponse, storedids_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodStoreResponse, error_),
  };
  CompositeFoodStoreResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CompositeFoodStoreResponse_descriptor_,
      CompositeFoodStoreResponse::default_instance_,
      CompositeFoodStoreResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodStoreResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodStoreResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CompositeFoodStoreResponse));
  CompositeFoodDeleteRequest_descriptor_ = file->message_type(4);
  static const int CompositeFoodDeleteRequest_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodDeleteRequest, deleteids_),
  };
  CompositeFoodDeleteRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CompositeFoodDeleteRequest_descriptor_,
      CompositeFoodDeleteRequest::default_instance_,
      CompositeFoodDeleteRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodDeleteRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodDeleteRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CompositeFoodDeleteRequest));
  CompositeFoodDeleteResponse_descriptor_ = file->message_type(5);
  static const int CompositeFoodDeleteResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodDeleteResponse, deletedids_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodDeleteResponse, error_),
  };
  CompositeFoodDeleteResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CompositeFoodDeleteResponse_descriptor_,
      CompositeFoodDeleteResponse::default_instance_,
      CompositeFoodDeleteResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodDeleteResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CompositeFoodDeleteResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CompositeFoodDeleteResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CompositeFoodLoadRequest_descriptor_, &CompositeFoodLoadRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CompositeFoodLoadResponse_descriptor_, &CompositeFoodLoadResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CompositeFoodStoreRequest_descriptor_, &CompositeFoodStoreRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CompositeFoodStoreResponse_descriptor_, &CompositeFoodStoreResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CompositeFoodDeleteRequest_descriptor_, &CompositeFoodDeleteRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CompositeFoodDeleteResponse_descriptor_, &CompositeFoodDeleteResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto() {
  delete CompositeFoodLoadRequest::default_instance_;
  delete CompositeFoodLoadRequest_reflection_;
  delete CompositeFoodLoadResponse::default_instance_;
  delete CompositeFoodLoadResponse_reflection_;
  delete CompositeFoodStoreRequest::default_instance_;
  delete CompositeFoodStoreRequest_reflection_;
  delete CompositeFoodStoreResponse::default_instance_;
  delete CompositeFoodStoreResponse_reflection_;
  delete CompositeFoodDeleteRequest::default_instance_;
  delete CompositeFoodDeleteRequest_reflection_;
  delete CompositeFoodDeleteResponse::default_instance_;
  delete CompositeFoodDeleteResponse_reflection_;
}

void protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_libnutrition_2fproto_2fdata_2fcomposite_5ffood_2eproto();
  ::protobuf_AddDesc_libnutrition_2fproto_2fservice_2ferror_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n8libnutrition/proto/service/composite_f"
    "ood_messages.proto\032,libnutrition/proto/d"
    "ata/composite_food.proto\032&libnutrition/p"
    "roto/service/error.proto\"\274\001\n\030CompositeFo"
    "odLoadRequest\022\023\n\004omit\030\001 \001(\010:\005false\022\032\n\013om"
    "itExpired\030\002 \001(\010:\005false\022\034\n\rnameAndIdOnly\030"
    "\003 \001(\010:\005false\022!\n\022includeDatesInName\030\004 \001(\010"
    ":\005false\022\024\n\014requestedIds\030\005 \003(\005\022\030\n\020request"
    "edUserIds\030\006 \003(\005\"^\n\031CompositeFoodLoadResp"
    "onse\022*\n\016compositeFoods\030\001 \003(\0132\022.Composite"
    "FoodData\022\025\n\005error\030d \001(\0132\006.Error\"G\n\031Compo"
    "siteFoodStoreRequest\022*\n\016compositeFoods\030\001"
    " \003(\0132\022.CompositeFoodData\"F\n\032CompositeFoo"
    "dStoreResponse\022\021\n\tstoredIds\030\001 \003(\005\022\025\n\005err"
    "or\030d \001(\0132\006.Error\"/\n\032CompositeFoodDeleteR"
    "equest\022\021\n\tdeleteIds\030\001 \003(\005\"H\n\033CompositeFo"
    "odDeleteResponse\022\022\n\ndeletedIds\030\001 \003(\005\022\025\n\005"
    "error\030d \001(\0132\006.Error", 699);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "libnutrition/proto/service/composite_food_messages.proto", &protobuf_RegisterTypes);
  CompositeFoodLoadRequest::default_instance_ = new CompositeFoodLoadRequest();
  CompositeFoodLoadResponse::default_instance_ = new CompositeFoodLoadResponse();
  CompositeFoodStoreRequest::default_instance_ = new CompositeFoodStoreRequest();
  CompositeFoodStoreResponse::default_instance_ = new CompositeFoodStoreResponse();
  CompositeFoodDeleteRequest::default_instance_ = new CompositeFoodDeleteRequest();
  CompositeFoodDeleteResponse::default_instance_ = new CompositeFoodDeleteResponse();
  CompositeFoodLoadRequest::default_instance_->InitAsDefaultInstance();
  CompositeFoodLoadResponse::default_instance_->InitAsDefaultInstance();
  CompositeFoodStoreRequest::default_instance_->InitAsDefaultInstance();
  CompositeFoodStoreResponse::default_instance_->InitAsDefaultInstance();
  CompositeFoodDeleteRequest::default_instance_->InitAsDefaultInstance();
  CompositeFoodDeleteResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto {
  StaticDescriptorInitializer_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto() {
    protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto();
  }
} static_descriptor_initializer_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int CompositeFoodLoadRequest::kOmitFieldNumber;
const int CompositeFoodLoadRequest::kOmitExpiredFieldNumber;
const int CompositeFoodLoadRequest::kNameAndIdOnlyFieldNumber;
const int CompositeFoodLoadRequest::kIncludeDatesInNameFieldNumber;
const int CompositeFoodLoadRequest::kRequestedIdsFieldNumber;
const int CompositeFoodLoadRequest::kRequestedUserIdsFieldNumber;
#endif  // !_MSC_VER

CompositeFoodLoadRequest::CompositeFoodLoadRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CompositeFoodLoadRequest::InitAsDefaultInstance() {
}

CompositeFoodLoadRequest::CompositeFoodLoadRequest(const CompositeFoodLoadRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CompositeFoodLoadRequest::SharedCtor() {
  _cached_size_ = 0;
  omit_ = false;
  omitexpired_ = false;
  nameandidonly_ = false;
  includedatesinname_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CompositeFoodLoadRequest::~CompositeFoodLoadRequest() {
  SharedDtor();
}

void CompositeFoodLoadRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CompositeFoodLoadRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CompositeFoodLoadRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CompositeFoodLoadRequest_descriptor_;
}

const CompositeFoodLoadRequest& CompositeFoodLoadRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto();  return *default_instance_;
}

CompositeFoodLoadRequest* CompositeFoodLoadRequest::default_instance_ = NULL;

CompositeFoodLoadRequest* CompositeFoodLoadRequest::New() const {
  return new CompositeFoodLoadRequest;
}

void CompositeFoodLoadRequest::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    omit_ = false;
    omitexpired_ = false;
    nameandidonly_ = false;
    includedatesinname_ = false;
  }
  requestedids_.Clear();
  requesteduserids_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CompositeFoodLoadRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool omit = 1 [default = false];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &omit_)));
          _set_bit(0);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_omitExpired;
        break;
      }
      
      // optional bool omitExpired = 2 [default = false];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_omitExpired:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &omitexpired_)));
          _set_bit(1);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_nameAndIdOnly;
        break;
      }
      
      // optional bool nameAndIdOnly = 3 [default = false];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_nameAndIdOnly:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &nameandidonly_)));
          _set_bit(2);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_includeDatesInName;
        break;
      }
      
      // optional bool includeDatesInName = 4 [default = false];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_includeDatesInName:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &includedatesinname_)));
          _set_bit(3);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_requestedIds;
        break;
      }
      
      // repeated int32 requestedIds = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_requestedIds:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 40, input, this->mutable_requestedids())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_requestedids())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_requestedIds;
        if (input->ExpectTag(48)) goto parse_requestedUserIds;
        break;
      }
      
      // repeated int32 requestedUserIds = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_requestedUserIds:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 48, input, this->mutable_requesteduserids())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_requesteduserids())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_requestedUserIds;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CompositeFoodLoadRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool omit = 1 [default = false];
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->omit(), output);
  }
  
  // optional bool omitExpired = 2 [default = false];
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->omitexpired(), output);
  }
  
  // optional bool nameAndIdOnly = 3 [default = false];
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->nameandidonly(), output);
  }
  
  // optional bool includeDatesInName = 4 [default = false];
  if (_has_bit(3)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->includedatesinname(), output);
  }
  
  // repeated int32 requestedIds = 5;
  for (int i = 0; i < this->requestedids_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      5, this->requestedids(i), output);
  }
  
  // repeated int32 requestedUserIds = 6;
  for (int i = 0; i < this->requesteduserids_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      6, this->requesteduserids(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CompositeFoodLoadRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool omit = 1 [default = false];
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->omit(), target);
  }
  
  // optional bool omitExpired = 2 [default = false];
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->omitexpired(), target);
  }
  
  // optional bool nameAndIdOnly = 3 [default = false];
  if (_has_bit(2)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->nameandidonly(), target);
  }
  
  // optional bool includeDatesInName = 4 [default = false];
  if (_has_bit(3)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->includedatesinname(), target);
  }
  
  // repeated int32 requestedIds = 5;
  for (int i = 0; i < this->requestedids_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(5, this->requestedids(i), target);
  }
  
  // repeated int32 requestedUserIds = 6;
  for (int i = 0; i < this->requesteduserids_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(6, this->requesteduserids(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CompositeFoodLoadRequest::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool omit = 1 [default = false];
    if (has_omit()) {
      total_size += 1 + 1;
    }
    
    // optional bool omitExpired = 2 [default = false];
    if (has_omitexpired()) {
      total_size += 1 + 1;
    }
    
    // optional bool nameAndIdOnly = 3 [default = false];
    if (has_nameandidonly()) {
      total_size += 1 + 1;
    }
    
    // optional bool includeDatesInName = 4 [default = false];
    if (has_includedatesinname()) {
      total_size += 1 + 1;
    }
    
  }
  // repeated int32 requestedIds = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->requestedids_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->requestedids(i));
    }
    total_size += 1 * this->requestedids_size() + data_size;
  }
  
  // repeated int32 requestedUserIds = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->requesteduserids_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->requesteduserids(i));
    }
    total_size += 1 * this->requesteduserids_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CompositeFoodLoadRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CompositeFoodLoadRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CompositeFoodLoadRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CompositeFoodLoadRequest::MergeFrom(const CompositeFoodLoadRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  requestedids_.MergeFrom(from.requestedids_);
  requesteduserids_.MergeFrom(from.requesteduserids_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_omit(from.omit());
    }
    if (from._has_bit(1)) {
      set_omitexpired(from.omitexpired());
    }
    if (from._has_bit(2)) {
      set_nameandidonly(from.nameandidonly());
    }
    if (from._has_bit(3)) {
      set_includedatesinname(from.includedatesinname());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CompositeFoodLoadRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CompositeFoodLoadRequest::CopyFrom(const CompositeFoodLoadRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompositeFoodLoadRequest::IsInitialized() const {
  
  return true;
}

void CompositeFoodLoadRequest::Swap(CompositeFoodLoadRequest* other) {
  if (other != this) {
    std::swap(omit_, other->omit_);
    std::swap(omitexpired_, other->omitexpired_);
    std::swap(nameandidonly_, other->nameandidonly_);
    std::swap(includedatesinname_, other->includedatesinname_);
    requestedids_.Swap(&other->requestedids_);
    requesteduserids_.Swap(&other->requesteduserids_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CompositeFoodLoadRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CompositeFoodLoadRequest_descriptor_;
  metadata.reflection = CompositeFoodLoadRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CompositeFoodLoadResponse::kCompositeFoodsFieldNumber;
const int CompositeFoodLoadResponse::kErrorFieldNumber;
#endif  // !_MSC_VER

CompositeFoodLoadResponse::CompositeFoodLoadResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CompositeFoodLoadResponse::InitAsDefaultInstance() {
  error_ = const_cast< ::Error*>(&::Error::default_instance());
}

CompositeFoodLoadResponse::CompositeFoodLoadResponse(const CompositeFoodLoadResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CompositeFoodLoadResponse::SharedCtor() {
  _cached_size_ = 0;
  error_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CompositeFoodLoadResponse::~CompositeFoodLoadResponse() {
  SharedDtor();
}

void CompositeFoodLoadResponse::SharedDtor() {
  if (this != default_instance_) {
    delete error_;
  }
}

void CompositeFoodLoadResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CompositeFoodLoadResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CompositeFoodLoadResponse_descriptor_;
}

const CompositeFoodLoadResponse& CompositeFoodLoadResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto();  return *default_instance_;
}

CompositeFoodLoadResponse* CompositeFoodLoadResponse::default_instance_ = NULL;

CompositeFoodLoadResponse* CompositeFoodLoadResponse::New() const {
  return new CompositeFoodLoadResponse;
}

void CompositeFoodLoadResponse::Clear() {
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (_has_bit(1)) {
      if (error_ != NULL) error_->::Error::Clear();
    }
  }
  compositefoods_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CompositeFoodLoadResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .CompositeFoodData compositeFoods = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_compositeFoods:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_compositefoods()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_compositeFoods;
        if (input->ExpectTag(802)) goto parse_error;
        break;
      }
      
      // optional .Error error = 100;
      case 100: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_error:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_error()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CompositeFoodLoadResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .CompositeFoodData compositeFoods = 1;
  for (int i = 0; i < this->compositefoods_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->compositefoods(i), output);
  }
  
  // optional .Error error = 100;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      100, this->error(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CompositeFoodLoadResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .CompositeFoodData compositeFoods = 1;
  for (int i = 0; i < this->compositefoods_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->compositefoods(i), target);
  }
  
  // optional .Error error = 100;
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        100, this->error(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CompositeFoodLoadResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional .Error error = 100;
    if (has_error()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->error());
    }
    
  }
  // repeated .CompositeFoodData compositeFoods = 1;
  total_size += 1 * this->compositefoods_size();
  for (int i = 0; i < this->compositefoods_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->compositefoods(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CompositeFoodLoadResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CompositeFoodLoadResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CompositeFoodLoadResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CompositeFoodLoadResponse::MergeFrom(const CompositeFoodLoadResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  compositefoods_.MergeFrom(from.compositefoods_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from._has_bit(1)) {
      mutable_error()->::Error::MergeFrom(from.error());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CompositeFoodLoadResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CompositeFoodLoadResponse::CopyFrom(const CompositeFoodLoadResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompositeFoodLoadResponse::IsInitialized() const {
  
  for (int i = 0; i < compositefoods_size(); i++) {
    if (!this->compositefoods(i).IsInitialized()) return false;
  }
  if (has_error()) {
    if (!this->error().IsInitialized()) return false;
  }
  return true;
}

void CompositeFoodLoadResponse::Swap(CompositeFoodLoadResponse* other) {
  if (other != this) {
    compositefoods_.Swap(&other->compositefoods_);
    std::swap(error_, other->error_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CompositeFoodLoadResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CompositeFoodLoadResponse_descriptor_;
  metadata.reflection = CompositeFoodLoadResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CompositeFoodStoreRequest::kCompositeFoodsFieldNumber;
#endif  // !_MSC_VER

CompositeFoodStoreRequest::CompositeFoodStoreRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CompositeFoodStoreRequest::InitAsDefaultInstance() {
}

CompositeFoodStoreRequest::CompositeFoodStoreRequest(const CompositeFoodStoreRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CompositeFoodStoreRequest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CompositeFoodStoreRequest::~CompositeFoodStoreRequest() {
  SharedDtor();
}

void CompositeFoodStoreRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CompositeFoodStoreRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CompositeFoodStoreRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CompositeFoodStoreRequest_descriptor_;
}

const CompositeFoodStoreRequest& CompositeFoodStoreRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto();  return *default_instance_;
}

CompositeFoodStoreRequest* CompositeFoodStoreRequest::default_instance_ = NULL;

CompositeFoodStoreRequest* CompositeFoodStoreRequest::New() const {
  return new CompositeFoodStoreRequest;
}

void CompositeFoodStoreRequest::Clear() {
  compositefoods_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CompositeFoodStoreRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .CompositeFoodData compositeFoods = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_compositeFoods:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_compositefoods()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_compositeFoods;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CompositeFoodStoreRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .CompositeFoodData compositeFoods = 1;
  for (int i = 0; i < this->compositefoods_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->compositefoods(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CompositeFoodStoreRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .CompositeFoodData compositeFoods = 1;
  for (int i = 0; i < this->compositefoods_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->compositefoods(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CompositeFoodStoreRequest::ByteSize() const {
  int total_size = 0;
  
  // repeated .CompositeFoodData compositeFoods = 1;
  total_size += 1 * this->compositefoods_size();
  for (int i = 0; i < this->compositefoods_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->compositefoods(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CompositeFoodStoreRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CompositeFoodStoreRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CompositeFoodStoreRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CompositeFoodStoreRequest::MergeFrom(const CompositeFoodStoreRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  compositefoods_.MergeFrom(from.compositefoods_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CompositeFoodStoreRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CompositeFoodStoreRequest::CopyFrom(const CompositeFoodStoreRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompositeFoodStoreRequest::IsInitialized() const {
  
  for (int i = 0; i < compositefoods_size(); i++) {
    if (!this->compositefoods(i).IsInitialized()) return false;
  }
  return true;
}

void CompositeFoodStoreRequest::Swap(CompositeFoodStoreRequest* other) {
  if (other != this) {
    compositefoods_.Swap(&other->compositefoods_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CompositeFoodStoreRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CompositeFoodStoreRequest_descriptor_;
  metadata.reflection = CompositeFoodStoreRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CompositeFoodStoreResponse::kStoredIdsFieldNumber;
const int CompositeFoodStoreResponse::kErrorFieldNumber;
#endif  // !_MSC_VER

CompositeFoodStoreResponse::CompositeFoodStoreResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CompositeFoodStoreResponse::InitAsDefaultInstance() {
  error_ = const_cast< ::Error*>(&::Error::default_instance());
}

CompositeFoodStoreResponse::CompositeFoodStoreResponse(const CompositeFoodStoreResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CompositeFoodStoreResponse::SharedCtor() {
  _cached_size_ = 0;
  error_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CompositeFoodStoreResponse::~CompositeFoodStoreResponse() {
  SharedDtor();
}

void CompositeFoodStoreResponse::SharedDtor() {
  if (this != default_instance_) {
    delete error_;
  }
}

void CompositeFoodStoreResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CompositeFoodStoreResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CompositeFoodStoreResponse_descriptor_;
}

const CompositeFoodStoreResponse& CompositeFoodStoreResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto();  return *default_instance_;
}

CompositeFoodStoreResponse* CompositeFoodStoreResponse::default_instance_ = NULL;

CompositeFoodStoreResponse* CompositeFoodStoreResponse::New() const {
  return new CompositeFoodStoreResponse;
}

void CompositeFoodStoreResponse::Clear() {
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (_has_bit(1)) {
      if (error_ != NULL) error_->::Error::Clear();
    }
  }
  storedids_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CompositeFoodStoreResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 storedIds = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_storedIds:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_storedids())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_storedids())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_storedIds;
        if (input->ExpectTag(802)) goto parse_error;
        break;
      }
      
      // optional .Error error = 100;
      case 100: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_error:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_error()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CompositeFoodStoreResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 storedIds = 1;
  for (int i = 0; i < this->storedids_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->storedids(i), output);
  }
  
  // optional .Error error = 100;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      100, this->error(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CompositeFoodStoreResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 storedIds = 1;
  for (int i = 0; i < this->storedids_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->storedids(i), target);
  }
  
  // optional .Error error = 100;
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        100, this->error(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CompositeFoodStoreResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional .Error error = 100;
    if (has_error()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->error());
    }
    
  }
  // repeated int32 storedIds = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->storedids_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->storedids(i));
    }
    total_size += 1 * this->storedids_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CompositeFoodStoreResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CompositeFoodStoreResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CompositeFoodStoreResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CompositeFoodStoreResponse::MergeFrom(const CompositeFoodStoreResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  storedids_.MergeFrom(from.storedids_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from._has_bit(1)) {
      mutable_error()->::Error::MergeFrom(from.error());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CompositeFoodStoreResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CompositeFoodStoreResponse::CopyFrom(const CompositeFoodStoreResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompositeFoodStoreResponse::IsInitialized() const {
  
  if (has_error()) {
    if (!this->error().IsInitialized()) return false;
  }
  return true;
}

void CompositeFoodStoreResponse::Swap(CompositeFoodStoreResponse* other) {
  if (other != this) {
    storedids_.Swap(&other->storedids_);
    std::swap(error_, other->error_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CompositeFoodStoreResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CompositeFoodStoreResponse_descriptor_;
  metadata.reflection = CompositeFoodStoreResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CompositeFoodDeleteRequest::kDeleteIdsFieldNumber;
#endif  // !_MSC_VER

CompositeFoodDeleteRequest::CompositeFoodDeleteRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CompositeFoodDeleteRequest::InitAsDefaultInstance() {
}

CompositeFoodDeleteRequest::CompositeFoodDeleteRequest(const CompositeFoodDeleteRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CompositeFoodDeleteRequest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CompositeFoodDeleteRequest::~CompositeFoodDeleteRequest() {
  SharedDtor();
}

void CompositeFoodDeleteRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CompositeFoodDeleteRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CompositeFoodDeleteRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CompositeFoodDeleteRequest_descriptor_;
}

const CompositeFoodDeleteRequest& CompositeFoodDeleteRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto();  return *default_instance_;
}

CompositeFoodDeleteRequest* CompositeFoodDeleteRequest::default_instance_ = NULL;

CompositeFoodDeleteRequest* CompositeFoodDeleteRequest::New() const {
  return new CompositeFoodDeleteRequest;
}

void CompositeFoodDeleteRequest::Clear() {
  deleteids_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CompositeFoodDeleteRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 deleteIds = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_deleteIds:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_deleteids())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_deleteids())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_deleteIds;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CompositeFoodDeleteRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 deleteIds = 1;
  for (int i = 0; i < this->deleteids_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->deleteids(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CompositeFoodDeleteRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 deleteIds = 1;
  for (int i = 0; i < this->deleteids_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->deleteids(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CompositeFoodDeleteRequest::ByteSize() const {
  int total_size = 0;
  
  // repeated int32 deleteIds = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->deleteids_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->deleteids(i));
    }
    total_size += 1 * this->deleteids_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CompositeFoodDeleteRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CompositeFoodDeleteRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CompositeFoodDeleteRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CompositeFoodDeleteRequest::MergeFrom(const CompositeFoodDeleteRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  deleteids_.MergeFrom(from.deleteids_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CompositeFoodDeleteRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CompositeFoodDeleteRequest::CopyFrom(const CompositeFoodDeleteRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompositeFoodDeleteRequest::IsInitialized() const {
  
  return true;
}

void CompositeFoodDeleteRequest::Swap(CompositeFoodDeleteRequest* other) {
  if (other != this) {
    deleteids_.Swap(&other->deleteids_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CompositeFoodDeleteRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CompositeFoodDeleteRequest_descriptor_;
  metadata.reflection = CompositeFoodDeleteRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CompositeFoodDeleteResponse::kDeletedIdsFieldNumber;
const int CompositeFoodDeleteResponse::kErrorFieldNumber;
#endif  // !_MSC_VER

CompositeFoodDeleteResponse::CompositeFoodDeleteResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CompositeFoodDeleteResponse::InitAsDefaultInstance() {
  error_ = const_cast< ::Error*>(&::Error::default_instance());
}

CompositeFoodDeleteResponse::CompositeFoodDeleteResponse(const CompositeFoodDeleteResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CompositeFoodDeleteResponse::SharedCtor() {
  _cached_size_ = 0;
  error_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CompositeFoodDeleteResponse::~CompositeFoodDeleteResponse() {
  SharedDtor();
}

void CompositeFoodDeleteResponse::SharedDtor() {
  if (this != default_instance_) {
    delete error_;
  }
}

void CompositeFoodDeleteResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CompositeFoodDeleteResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CompositeFoodDeleteResponse_descriptor_;
}

const CompositeFoodDeleteResponse& CompositeFoodDeleteResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_libnutrition_2fproto_2fservice_2fcomposite_5ffood_5fmessages_2eproto();  return *default_instance_;
}

CompositeFoodDeleteResponse* CompositeFoodDeleteResponse::default_instance_ = NULL;

CompositeFoodDeleteResponse* CompositeFoodDeleteResponse::New() const {
  return new CompositeFoodDeleteResponse;
}

void CompositeFoodDeleteResponse::Clear() {
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (_has_bit(1)) {
      if (error_ != NULL) error_->::Error::Clear();
    }
  }
  deletedids_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CompositeFoodDeleteResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 deletedIds = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_deletedIds:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_deletedids())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_deletedids())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_deletedIds;
        if (input->ExpectTag(802)) goto parse_error;
        break;
      }
      
      // optional .Error error = 100;
      case 100: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_error:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_error()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CompositeFoodDeleteResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated int32 deletedIds = 1;
  for (int i = 0; i < this->deletedids_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->deletedids(i), output);
  }
  
  // optional .Error error = 100;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      100, this->error(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CompositeFoodDeleteResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated int32 deletedIds = 1;
  for (int i = 0; i < this->deletedids_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->deletedids(i), target);
  }
  
  // optional .Error error = 100;
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        100, this->error(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CompositeFoodDeleteResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional .Error error = 100;
    if (has_error()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->error());
    }
    
  }
  // repeated int32 deletedIds = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->deletedids_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->deletedids(i));
    }
    total_size += 1 * this->deletedids_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CompositeFoodDeleteResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CompositeFoodDeleteResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CompositeFoodDeleteResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CompositeFoodDeleteResponse::MergeFrom(const CompositeFoodDeleteResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  deletedids_.MergeFrom(from.deletedids_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from._has_bit(1)) {
      mutable_error()->::Error::MergeFrom(from.error());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CompositeFoodDeleteResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CompositeFoodDeleteResponse::CopyFrom(const CompositeFoodDeleteResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CompositeFoodDeleteResponse::IsInitialized() const {
  
  if (has_error()) {
    if (!this->error().IsInitialized()) return false;
  }
  return true;
}

void CompositeFoodDeleteResponse::Swap(CompositeFoodDeleteResponse* other) {
  if (other != this) {
    deletedids_.Swap(&other->deletedids_);
    std::swap(error_, other->error_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CompositeFoodDeleteResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CompositeFoodDeleteResponse_descriptor_;
  metadata.reflection = CompositeFoodDeleteResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
