// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: libnutrition/proto/service/specialized_unit_messages.proto

#ifndef PROTOBUF_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto__INCLUDED
#define PROTOBUF_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "libnutrition/proto/data/specialized_unit.pb.h"
#include "libnutrition/proto/service/error.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();
void protobuf_AssignDesc_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();
void protobuf_ShutdownFile_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();

class SpecializedUnitLoadResponse;
class SpecializedUnitLoadRequest;

// ===================================================================

class SpecializedUnitLoadResponse : public ::google::protobuf::Message {
 public:
  SpecializedUnitLoadResponse();
  virtual ~SpecializedUnitLoadResponse();
  
  SpecializedUnitLoadResponse(const SpecializedUnitLoadResponse& from);
  
  inline SpecializedUnitLoadResponse& operator=(const SpecializedUnitLoadResponse& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SpecializedUnitLoadResponse& default_instance();
  
  void Swap(SpecializedUnitLoadResponse* other);
  
  // implements Message ----------------------------------------------
  
  SpecializedUnitLoadResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpecializedUnitLoadResponse& from);
  void MergeFrom(const SpecializedUnitLoadResponse& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .SpecializedUnitData specializedUnits = 1;
  inline int specializedunits_size() const;
  inline void clear_specializedunits();
  static const int kSpecializedUnitsFieldNumber = 1;
  inline const ::SpecializedUnitData& specializedunits(int index) const;
  inline ::SpecializedUnitData* mutable_specializedunits(int index);
  inline ::SpecializedUnitData* add_specializedunits();
  inline const ::google::protobuf::RepeatedPtrField< ::SpecializedUnitData >&
      specializedunits() const;
  inline ::google::protobuf::RepeatedPtrField< ::SpecializedUnitData >*
      mutable_specializedunits();
  
  // optional .Error error = 100;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 100;
  inline const ::Error& error() const;
  inline ::Error* mutable_error();
  
  // @@protoc_insertion_point(class_scope:SpecializedUnitLoadResponse)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::SpecializedUnitData > specializedunits_;
  ::Error* error_;
  friend void  protobuf_AddDesc_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();
  friend void protobuf_AssignDesc_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static SpecializedUnitLoadResponse* default_instance_;
};
// -------------------------------------------------------------------

class SpecializedUnitLoadRequest : public ::google::protobuf::Message {
 public:
  SpecializedUnitLoadRequest();
  virtual ~SpecializedUnitLoadRequest();
  
  SpecializedUnitLoadRequest(const SpecializedUnitLoadRequest& from);
  
  inline SpecializedUnitLoadRequest& operator=(const SpecializedUnitLoadRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SpecializedUnitLoadRequest& default_instance();
  
  void Swap(SpecializedUnitLoadRequest* other);
  
  // implements Message ----------------------------------------------
  
  SpecializedUnitLoadRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpecializedUnitLoadRequest& from);
  void MergeFrom(const SpecializedUnitLoadRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional bool omit = 1 [default = false];
  inline bool has_omit() const;
  inline void clear_omit();
  static const int kOmitFieldNumber = 1;
  inline bool omit() const;
  inline void set_omit(bool value);
  
  // repeated int32 requestedSingleFoodIds = 2;
  inline int requestedsinglefoodids_size() const;
  inline void clear_requestedsinglefoodids();
  static const int kRequestedSingleFoodIdsFieldNumber = 2;
  inline ::google::protobuf::int32 requestedsinglefoodids(int index) const;
  inline void set_requestedsinglefoodids(int index, ::google::protobuf::int32 value);
  inline void add_requestedsinglefoodids(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      requestedsinglefoodids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_requestedsinglefoodids();
  
  // repeated .SpecializedUnitIdentifier requestedIds = 3;
  inline int requestedids_size() const;
  inline void clear_requestedids();
  static const int kRequestedIdsFieldNumber = 3;
  inline const ::SpecializedUnitIdentifier& requestedids(int index) const;
  inline ::SpecializedUnitIdentifier* mutable_requestedids(int index);
  inline ::SpecializedUnitIdentifier* add_requestedids();
  inline const ::google::protobuf::RepeatedPtrField< ::SpecializedUnitIdentifier >&
      requestedids() const;
  inline ::google::protobuf::RepeatedPtrField< ::SpecializedUnitIdentifier >*
      mutable_requestedids();
  
  // @@protoc_insertion_point(class_scope:SpecializedUnitLoadRequest)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  bool omit_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > requestedsinglefoodids_;
  ::google::protobuf::RepeatedPtrField< ::SpecializedUnitIdentifier > requestedids_;
  friend void  protobuf_AddDesc_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();
  friend void protobuf_AssignDesc_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();
  friend void protobuf_ShutdownFile_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static SpecializedUnitLoadRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// SpecializedUnitLoadResponse

// repeated .SpecializedUnitData specializedUnits = 1;
inline int SpecializedUnitLoadResponse::specializedunits_size() const {
  return specializedunits_.size();
}
inline void SpecializedUnitLoadResponse::clear_specializedunits() {
  specializedunits_.Clear();
}
inline const ::SpecializedUnitData& SpecializedUnitLoadResponse::specializedunits(int index) const {
  return specializedunits_.Get(index);
}
inline ::SpecializedUnitData* SpecializedUnitLoadResponse::mutable_specializedunits(int index) {
  return specializedunits_.Mutable(index);
}
inline ::SpecializedUnitData* SpecializedUnitLoadResponse::add_specializedunits() {
  return specializedunits_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SpecializedUnitData >&
SpecializedUnitLoadResponse::specializedunits() const {
  return specializedunits_;
}
inline ::google::protobuf::RepeatedPtrField< ::SpecializedUnitData >*
SpecializedUnitLoadResponse::mutable_specializedunits() {
  return &specializedunits_;
}

// optional .Error error = 100;
inline bool SpecializedUnitLoadResponse::has_error() const {
  return _has_bit(1);
}
inline void SpecializedUnitLoadResponse::clear_error() {
  if (error_ != NULL) error_->::Error::Clear();
  _clear_bit(1);
}
inline const ::Error& SpecializedUnitLoadResponse::error() const {
  return error_ != NULL ? *error_ : *default_instance_->error_;
}
inline ::Error* SpecializedUnitLoadResponse::mutable_error() {
  _set_bit(1);
  if (error_ == NULL) error_ = new ::Error;
  return error_;
}

// -------------------------------------------------------------------

// SpecializedUnitLoadRequest

// optional bool omit = 1 [default = false];
inline bool SpecializedUnitLoadRequest::has_omit() const {
  return _has_bit(0);
}
inline void SpecializedUnitLoadRequest::clear_omit() {
  omit_ = false;
  _clear_bit(0);
}
inline bool SpecializedUnitLoadRequest::omit() const {
  return omit_;
}
inline void SpecializedUnitLoadRequest::set_omit(bool value) {
  _set_bit(0);
  omit_ = value;
}

// repeated int32 requestedSingleFoodIds = 2;
inline int SpecializedUnitLoadRequest::requestedsinglefoodids_size() const {
  return requestedsinglefoodids_.size();
}
inline void SpecializedUnitLoadRequest::clear_requestedsinglefoodids() {
  requestedsinglefoodids_.Clear();
}
inline ::google::protobuf::int32 SpecializedUnitLoadRequest::requestedsinglefoodids(int index) const {
  return requestedsinglefoodids_.Get(index);
}
inline void SpecializedUnitLoadRequest::set_requestedsinglefoodids(int index, ::google::protobuf::int32 value) {
  requestedsinglefoodids_.Set(index, value);
}
inline void SpecializedUnitLoadRequest::add_requestedsinglefoodids(::google::protobuf::int32 value) {
  requestedsinglefoodids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SpecializedUnitLoadRequest::requestedsinglefoodids() const {
  return requestedsinglefoodids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SpecializedUnitLoadRequest::mutable_requestedsinglefoodids() {
  return &requestedsinglefoodids_;
}

// repeated .SpecializedUnitIdentifier requestedIds = 3;
inline int SpecializedUnitLoadRequest::requestedids_size() const {
  return requestedids_.size();
}
inline void SpecializedUnitLoadRequest::clear_requestedids() {
  requestedids_.Clear();
}
inline const ::SpecializedUnitIdentifier& SpecializedUnitLoadRequest::requestedids(int index) const {
  return requestedids_.Get(index);
}
inline ::SpecializedUnitIdentifier* SpecializedUnitLoadRequest::mutable_requestedids(int index) {
  return requestedids_.Mutable(index);
}
inline ::SpecializedUnitIdentifier* SpecializedUnitLoadRequest::add_requestedids() {
  return requestedids_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SpecializedUnitIdentifier >&
SpecializedUnitLoadRequest::requestedids() const {
  return requestedids_;
}
inline ::google::protobuf::RepeatedPtrField< ::SpecializedUnitIdentifier >*
SpecializedUnitLoadRequest::mutable_requestedids() {
  return &requestedids_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_libnutrition_2fproto_2fservice_2fspecialized_5funit_5fmessages_2eproto__INCLUDED
