// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "libnutrition/proto/service/unit_messages.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* UnitLoadRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UnitLoadRequest_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* UnitLoadRequest_Dimension_descriptor_ = NULL;
const ::google::protobuf::Descriptor* UnitLoadResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UnitLoadResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto() {
  protobuf_AddDesc_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "libnutrition/proto/service/unit_messages.proto");
  GOOGLE_CHECK(file != NULL);
  UnitLoadRequest_descriptor_ = file->message_type(0);
  static const int UnitLoadRequest_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadRequest, omit_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadRequest, all_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadRequest, requesteddimensions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadRequest, requestedabbreviations_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadRequest, basicunitsonly_),
  };
  UnitLoadRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UnitLoadRequest_descriptor_,
      UnitLoadRequest::default_instance_,
      UnitLoadRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UnitLoadRequest));
  UnitLoadRequest_Dimension_descriptor_ = UnitLoadRequest_descriptor_->enum_type(0);
  UnitLoadResponse_descriptor_ = file->message_type(1);
  static const int UnitLoadResponse_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadResponse, units_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadResponse, error_),
  };
  UnitLoadResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UnitLoadResponse_descriptor_,
      UnitLoadResponse::default_instance_,
      UnitLoadResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UnitLoadResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UnitLoadResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UnitLoadRequest_descriptor_, &UnitLoadRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UnitLoadResponse_descriptor_, &UnitLoadResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto() {
  delete UnitLoadRequest::default_instance_;
  delete UnitLoadRequest_reflection_;
  delete UnitLoadResponse::default_instance_;
  delete UnitLoadResponse_reflection_;
}

void protobuf_AddDesc_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_libnutrition_2fproto_2fdata_2funit_2eproto();
  ::protobuf_AddDesc_libnutrition_2fproto_2fservice_2ferror_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n.libnutrition/proto/service/unit_messag"
    "es.proto\032\"libnutrition/proto/data/unit.p"
    "roto\032&libnutrition/proto/service/error.p"
    "roto\"\206\002\n\017UnitLoadRequest\022\023\n\004omit\030\001 \001(\010:\005"
    "false\022\022\n\003all\030\002 \001(\010:\005false\0227\n\023requestedDi"
    "mensions\030\003 \003(\0162\032.UnitLoadRequest.Dimensi"
    "on\022\036\n\026requestedAbbreviations\030\004 \003(\t\022\035\n\016ba"
    "sicUnitsOnly\030\005 \001(\010:\005false\"R\n\tDimension\022\n"
    "\n\006Weight\020\000\022\n\n\006Volume\020\001\022\014\n\010Quantity\020\002\022\013\n\007"
    "Serving\020\003\022\n\n\006Energy\020\004\022\006\n\002IU\020\005\"C\n\020UnitLoa"
    "dResponse\022\030\n\005units\030\001 \003(\0132\t.UnitData\022\025\n\005e"
    "rror\030d \001(\0132\006.Error", 458);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "libnutrition/proto/service/unit_messages.proto", &protobuf_RegisterTypes);
  UnitLoadRequest::default_instance_ = new UnitLoadRequest();
  UnitLoadResponse::default_instance_ = new UnitLoadResponse();
  UnitLoadRequest::default_instance_->InitAsDefaultInstance();
  UnitLoadResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto {
  StaticDescriptorInitializer_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto() {
    protobuf_AddDesc_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto();
  }
} static_descriptor_initializer_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto_;


// ===================================================================

const ::google::protobuf::EnumDescriptor* UnitLoadRequest_Dimension_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UnitLoadRequest_Dimension_descriptor_;
}
bool UnitLoadRequest_Dimension_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const UnitLoadRequest_Dimension UnitLoadRequest::Weight;
const UnitLoadRequest_Dimension UnitLoadRequest::Volume;
const UnitLoadRequest_Dimension UnitLoadRequest::Quantity;
const UnitLoadRequest_Dimension UnitLoadRequest::Serving;
const UnitLoadRequest_Dimension UnitLoadRequest::Energy;
const UnitLoadRequest_Dimension UnitLoadRequest::IU;
const UnitLoadRequest_Dimension UnitLoadRequest::Dimension_MIN;
const UnitLoadRequest_Dimension UnitLoadRequest::Dimension_MAX;
const int UnitLoadRequest::Dimension_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int UnitLoadRequest::kOmitFieldNumber;
const int UnitLoadRequest::kAllFieldNumber;
const int UnitLoadRequest::kRequestedDimensionsFieldNumber;
const int UnitLoadRequest::kRequestedAbbreviationsFieldNumber;
const int UnitLoadRequest::kBasicUnitsOnlyFieldNumber;
#endif  // !_MSC_VER

UnitLoadRequest::UnitLoadRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void UnitLoadRequest::InitAsDefaultInstance() {
}

UnitLoadRequest::UnitLoadRequest(const UnitLoadRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void UnitLoadRequest::SharedCtor() {
  _cached_size_ = 0;
  omit_ = false;
  all_ = false;
  basicunitsonly_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UnitLoadRequest::~UnitLoadRequest() {
  SharedDtor();
}

void UnitLoadRequest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void UnitLoadRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UnitLoadRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UnitLoadRequest_descriptor_;
}

const UnitLoadRequest& UnitLoadRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto();  return *default_instance_;
}

UnitLoadRequest* UnitLoadRequest::default_instance_ = NULL;

UnitLoadRequest* UnitLoadRequest::New() const {
  return new UnitLoadRequest;
}

void UnitLoadRequest::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    omit_ = false;
    all_ = false;
    basicunitsonly_ = false;
  }
  requesteddimensions_.Clear();
  requestedabbreviations_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UnitLoadRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool omit = 1 [default = false];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &omit_)));
          _set_bit(0);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_all;
        break;
      }
      
      // optional bool all = 2 [default = false];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_all:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &all_)));
          _set_bit(1);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_requestedDimensions;
        break;
      }
      
      // repeated .UnitLoadRequest.Dimension requestedDimensions = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_requestedDimensions:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::UnitLoadRequest_Dimension_IsValid(value)) {
            add_requesteddimensions(static_cast< ::UnitLoadRequest_Dimension >(value));
          } else {
            mutable_unknown_fields()->AddVarint(3, value);
          }
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedEnumNoInline(
                 input,
                 &::UnitLoadRequest_Dimension_IsValid,
                 this->mutable_requesteddimensions())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_requestedDimensions;
        if (input->ExpectTag(34)) goto parse_requestedAbbreviations;
        break;
      }
      
      // repeated string requestedAbbreviations = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_requestedAbbreviations:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_requestedabbreviations()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->requestedabbreviations(0).data(), this->requestedabbreviations(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_requestedAbbreviations;
        if (input->ExpectTag(40)) goto parse_basicUnitsOnly;
        break;
      }
      
      // optional bool basicUnitsOnly = 5 [default = false];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_basicUnitsOnly:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &basicunitsonly_)));
          _set_bit(4);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void UnitLoadRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool omit = 1 [default = false];
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->omit(), output);
  }
  
  // optional bool all = 2 [default = false];
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->all(), output);
  }
  
  // repeated .UnitLoadRequest.Dimension requestedDimensions = 3;
  for (int i = 0; i < this->requesteddimensions_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->requesteddimensions(i), output);
  }
  
  // repeated string requestedAbbreviations = 4;
  for (int i = 0; i < this->requestedabbreviations_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->requestedabbreviations(i).data(), this->requestedabbreviations(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->requestedabbreviations(i), output);
  }
  
  // optional bool basicUnitsOnly = 5 [default = false];
  if (_has_bit(4)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->basicunitsonly(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UnitLoadRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool omit = 1 [default = false];
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->omit(), target);
  }
  
  // optional bool all = 2 [default = false];
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->all(), target);
  }
  
  // repeated .UnitLoadRequest.Dimension requestedDimensions = 3;
  for (int i = 0; i < this->requesteddimensions_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->requesteddimensions(i), target);
  }
  
  // repeated string requestedAbbreviations = 4;
  for (int i = 0; i < this->requestedabbreviations_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->requestedabbreviations(i).data(), this->requestedabbreviations(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->requestedabbreviations(i), target);
  }
  
  // optional bool basicUnitsOnly = 5 [default = false];
  if (_has_bit(4)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->basicunitsonly(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UnitLoadRequest::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool omit = 1 [default = false];
    if (has_omit()) {
      total_size += 1 + 1;
    }
    
    // optional bool all = 2 [default = false];
    if (has_all()) {
      total_size += 1 + 1;
    }
    
    // optional bool basicUnitsOnly = 5 [default = false];
    if (has_basicunitsonly()) {
      total_size += 1 + 1;
    }
    
  }
  // repeated .UnitLoadRequest.Dimension requestedDimensions = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->requesteddimensions_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::EnumSize(
        this->requesteddimensions(i));
    }
    total_size += 1 * this->requesteddimensions_size() + data_size;
  }
  
  // repeated string requestedAbbreviations = 4;
  total_size += 1 * this->requestedabbreviations_size();
  for (int i = 0; i < this->requestedabbreviations_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->requestedabbreviations(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UnitLoadRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UnitLoadRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UnitLoadRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UnitLoadRequest::MergeFrom(const UnitLoadRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  requesteddimensions_.MergeFrom(from.requesteddimensions_);
  requestedabbreviations_.MergeFrom(from.requestedabbreviations_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_omit(from.omit());
    }
    if (from._has_bit(1)) {
      set_all(from.all());
    }
    if (from._has_bit(4)) {
      set_basicunitsonly(from.basicunitsonly());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UnitLoadRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UnitLoadRequest::CopyFrom(const UnitLoadRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnitLoadRequest::IsInitialized() const {
  
  return true;
}

void UnitLoadRequest::Swap(UnitLoadRequest* other) {
  if (other != this) {
    std::swap(omit_, other->omit_);
    std::swap(all_, other->all_);
    requesteddimensions_.Swap(&other->requesteddimensions_);
    requestedabbreviations_.Swap(&other->requestedabbreviations_);
    std::swap(basicunitsonly_, other->basicunitsonly_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UnitLoadRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UnitLoadRequest_descriptor_;
  metadata.reflection = UnitLoadRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int UnitLoadResponse::kUnitsFieldNumber;
const int UnitLoadResponse::kErrorFieldNumber;
#endif  // !_MSC_VER

UnitLoadResponse::UnitLoadResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void UnitLoadResponse::InitAsDefaultInstance() {
  error_ = const_cast< ::Error*>(&::Error::default_instance());
}

UnitLoadResponse::UnitLoadResponse(const UnitLoadResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void UnitLoadResponse::SharedCtor() {
  _cached_size_ = 0;
  error_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UnitLoadResponse::~UnitLoadResponse() {
  SharedDtor();
}

void UnitLoadResponse::SharedDtor() {
  if (this != default_instance_) {
    delete error_;
  }
}

void UnitLoadResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UnitLoadResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UnitLoadResponse_descriptor_;
}

const UnitLoadResponse& UnitLoadResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_libnutrition_2fproto_2fservice_2funit_5fmessages_2eproto();  return *default_instance_;
}

UnitLoadResponse* UnitLoadResponse::default_instance_ = NULL;

UnitLoadResponse* UnitLoadResponse::New() const {
  return new UnitLoadResponse;
}

void UnitLoadResponse::Clear() {
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (_has_bit(1)) {
      if (error_ != NULL) error_->::Error::Clear();
    }
  }
  units_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UnitLoadResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .UnitData units = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_units:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_units()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_units;
        if (input->ExpectTag(802)) goto parse_error;
        break;
      }
      
      // optional .Error error = 100;
      case 100: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_error:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_error()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void UnitLoadResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .UnitData units = 1;
  for (int i = 0; i < this->units_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->units(i), output);
  }
  
  // optional .Error error = 100;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      100, this->error(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* UnitLoadResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .UnitData units = 1;
  for (int i = 0; i < this->units_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->units(i), target);
  }
  
  // optional .Error error = 100;
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        100, this->error(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int UnitLoadResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional .Error error = 100;
    if (has_error()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->error());
    }
    
  }
  // repeated .UnitData units = 1;
  total_size += 1 * this->units_size();
  for (int i = 0; i < this->units_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->units(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UnitLoadResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UnitLoadResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UnitLoadResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UnitLoadResponse::MergeFrom(const UnitLoadResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  units_.MergeFrom(from.units_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from._has_bit(1)) {
      mutable_error()->::Error::MergeFrom(from.error());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UnitLoadResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UnitLoadResponse::CopyFrom(const UnitLoadResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnitLoadResponse::IsInitialized() const {
  
  if (has_error()) {
    if (!this->error().IsInitialized()) return false;
  }
  return true;
}

void UnitLoadResponse::Swap(UnitLoadResponse* other) {
  if (other != this) {
    units_.Swap(&other->units_);
    std::swap(error_, other->error_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UnitLoadResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UnitLoadResponse_descriptor_;
  metadata.reflection = UnitLoadResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
